####Launches at point of Ec2 instance discovery tag match by Lambda function, deploys ec2 monitoring infrastructure
AWSTemplateFormatVersion: 2010-09-09
Parameters:
    volumeid:
        Type: String    
    instanceid:
        Type: String
    buildid:
        Type: String
    tagvalue:
        Type: String
Resources:
    UsageMonitorAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmName: !Sub '${tagvalue}-CPUutil-${instanceid}'
            Namespace: AWS/EC2
            Dimensions: 
                -   Name: 'InstanceId'
                    Value: !Ref instanceid
            MetricName: CPUUtilization
            Threshold: 5 #set for testing purposes
            Statistic:  Average
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Period: 180
            EvaluationPeriods: 1
            AlarmActions: 
                - Fn::ImportValue: !Sub 'Main-Event-Stack${buildid}-topicarn'
                - !Sub 'arn:aws:automate:${AWS::Region}:ec2:reboot'

                     
